dependencies {
    jarJar libs.fishLib
    implementation(libs.fishLib) {
        transitive = false
    }

    implementation libs.kotlinForForge
    implementation libs.ae2
    implementation libs.guideME
    implementation libs.glodium
    implementation libs.extendedAE
    implementation libs.advancedAE
    implementation libs.ae2wt
    implementation libs.jade
    implementation libs.jech
    implementation libs.emi
    implementation libs.jei
    implementation libs.ae2Jei
    implementation libs.ftbTeams
    implementation libs.ftbLibrary
    implementation libs.packagedAuto
    implementation libs.valhelsiaCore

    if (System.getenv("GITHUB_RUN_NUMBER") == null)
        compileOnly libs.forbiddenArcanusSource
    else compileOnly libs.forbiddenArcanus

    compileOnly libs.appliedFlux
    compileOnly libs.megaCells
    compileOnly libs.mekanism
    compileOnly libs.appliedMekanistics
    compileOnly libs.curios
    compileOnly libs.kubejs
    compileOnly libs.rei

    runtimeOnly libs.forbiddenArcanus
    runtimeOnly libs.geckolib
    runtimeOnly libs.appliedFlux
    runtimeOnly libs.megaCells
    runtimeOnly libs.mekanism
    runtimeOnly libs.appliedMekanistics
    runtimeOnly libs.curios
    runtimeOnly libs.architectury
    runtimeOnly libs.modernUI
}

repositories {
    mavenLocal()
    maven {
        name = "FishMaven"
        url = uri("https://repo.repsy.io/xianyu_fish/fishmaven")
    }
    maven {
        name = "TerraformersMC"
        url = uri("https://maven.terraformersmc.com/")
    }
    maven {
        name = "CurseMaven"
        url = uri("https://www.cursemaven.com")
    }
    maven {
        name = "ModMaven"
        url = uri("https://modmaven.dev/")
    }
    maven {
        name = "FTB Maven"
        url = uri("https://maven.ftb.dev/releases")
    }
    maven {
        name = "Kotlin for Forge"
        url = uri("https://thedarkcolour.github.io/KotlinForForge/")
    }
    maven {
        url = uri("https://maven.shedaniel.me/")
    }
    maven {
        url = uri("https://maven.architectury.dev/")
    }
    maven {
        url = uri("https://maven.latvian.dev/releases/")
    }
    maven {
        url = uri("https://maven.crystaelix.com/#/releases/")
    }
    mavenCentral()
}